module Cheatorious
  module Writer    
    class Text
      def initialize(cheatsheet_info = {})
        @info          = cheatsheet_info
        @section_stack = []
        @indentation   = ""
      end
      
      def header
        line
        line "-" * 80
        line "#{@info[:name]} (#{@info[:version]})"
        line
        line "Author     : #{@info[:name]}"
        line "Description: #{@info[:description]}"
        line "-" * 80
        line
      end
      
      def footer
        line
        line "-" * 80
        line "generated by Cheatorious (https://github.com/lfcipriani/cheatorious)"
      end
      
      def section_start(section)
        @section_stack.push(section)
        line indentation("-") + " #{section}"
      end
      
      def section_end
        @section_stack.pop
      end
      
      def entry(name, *values)
        e = "#{indentation(" ")} - #{name}: "
        e << values.join(", ")
        line e
      end
      
      def write!
      end
      
    private
    
      def line(str = "")
        puts str + "\n"
      end
      
      def indentation(char)
        char * 2 * @section_stack.size
      end
    end
  end
end
